name: Build provider runtime images

permissions:
  id-token: write
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  provider-images-build:
    runs-on: depot-ubuntu-22.04
    concurrency:
      group: provider-images-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Depot CLI
        uses: depot/setup-action@v1
        with:
          oidc: true

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        env:
          IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'main' }}
          IMAGE_PUSH: ${{ github.event_name != 'pull_request' }}
        run: |
          make all-images \
            IMAGE_TAG="${IMAGE_TAG}" \
            IMAGE_PUSH="${IMAGE_PUSH}" \
            IMAGE_PLATFORMS=linux/amd64,linux/arm64 \
            IMAGE_BUILD_COMMAND="depot build --project bbqjs4tj1g"

      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.8.1
        with:
          cosign-release: "v2.4.3"

      - name: Sign Images
        if: github.event_name != 'pull_request'
        env:
          IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'main' }}
        run: |
          set -e
          for provider_dir in $(make -s provider-dirs); do
            cosign sign --yes "ghcr.io/obot-platform/providers/${provider_dir}:${IMAGE_TAG}"
          done
